### ISSUE TITLE
rake test --  results in an error

### ISSUE THREAD

**Issue by saket424** [TwilioDevEd/ivr-phone-tree-rails#10]
I am using ruby 2.1.4 and get the following error

anand@awrtc:~/twilio/ivr-phone-tree-rails$ rake test
rake aborted!
NoMethodError: undefined method `fixtures' for ActiveSupport::TestCase:Class
/home/anand/twilio/ivr-phone-tree-rails/test/test_helper.rb:7:in `<class:TestCase>'
/home/anand/twilio/ivr-phone-tree-rails/test/test_helper.rb:5:in `<top (required)>'
/home/anand/twilio/ivr-phone-tree-rails/test/controllers/twilio_controller_test.rb:1:in `require'
/home/anand/twilio/ivr-phone-tree-rails/test/controllers/twilio_controller_test.rb:1:in `<top (required)>'
/home/anand/.rvm/gems/ruby-2.1.4/gems/railties-4.1.6/lib/rails/test_unit/sub_test_task.rb:114:in `require'
/home/anand/.rvm/gems/ruby-2.1.4/gems/railties-4.1.6/lib/rails/test_unit/sub_test_task.rb:114:in `block (3 levels) in define'
/home/anand/.rvm/gems/ruby-2.1.4/gems/railties-4.1.6/lib/rails/test_unit/sub_test_task.rb:114:in `each'
/home/anand/.rvm/gems/ruby-2.1.4/gems/railties-4.1.6/lib/rails/test_unit/sub_test_task.rb:114:in `block (2 levels) in define'
/home/anand/.rvm/gems/ruby-2.1.4/gems/railties-4.1.6/lib/rails/test_unit/sub_test_task.rb:113:in `each'
/home/anand/.rvm/gems/ruby-2.1.4/gems/railties-4.1.6/lib/rails/test_unit/sub_test_task.rb:113:in `block in define'
/home/anand/.rvm/gems/ruby-2.1.4/gems/railties-4.1.6/lib/rails/test_unit/sub_test_task.rb:20:in `invoke_rake_task'
/home/anand/.rvm/gems/ruby-2.1.4/gems/railties-4.1.6/lib/rails/test_unit/testing.rake:8:in `block in <top (required)>'
/home/anand/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `eval'
/home/anand/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => test:run => test:functionals
(See full trace by running task with --trace)

**Comment by jarodreyes** [comment]
Fixed, Thanks!
