### ISSUE TITLE
Failure on test suite

### ISSUE THREAD

**Issue by acamino** [TwilioDevEd/ivr-phone-tree-rails#12]
After fixing the issue #10 I found this failure.

<img width="604" alt="1__zsh" src="https://cloud.githubusercontent.com/assets/957202/10126628/9cf46494-655b-11e5-89e4-0acdbf8e864b.png">

This [assertion](https://github.com/TwilioDevEd/ivr-phone-tree-rails/blob/4006944c7b7271042257cc7927494fbe7a80d3a2/test/controllers/twilio_controller_test.rb#L39):
```ruby
test "/planets should Play something then Hangup when 2 is chosen" do
  get :planet_selection, From: "15556505813", Digits: '2'
  assert response.body.include? "Play"
  # ...
```

doesn't match with the implementation of [`TwilioController#planet_selection`](https://github.com/TwilioDevEd/ivr-phone-tree-rails/blob/4006944c7b7271042257cc7927494fbe7a80d3a2/app/controllers/twilio_controller.rb#L60-L61):
```ruby
case user_selection
when "2"
  twiml_dial("+12024173378")
when "3"
# ...

def twiml_dial(phone_number)
  response = Twilio::TwiML::Response.new do |r|
    r.Dial phone_number
  end

  render text: response.text
end
```
Would you mind checking this out please?

**Comment by jarodreyes** [comment]
Fixed: bab08d
