### ISSUE TITLE
 `list_planets` could be private?

### ISSUE THREAD

**Issue by acamino** [TwilioDevEd/ivr-phone-tree-rails#13]
@jarodreyes I think [`list_planets`](https://github.com/TwilioDevEd/ivr-phone-tree-rails/blob/4006944c7b7271042257cc7927494fbe7a80d3a2/app/controllers/twilio_controller.rb#L41-L53) should be `private`, since it is not being exposed through the public API, what do you think?

If you agree and of course if you don't mind I can do the change and create a PR for that.

**Comment by jarodreyes** [comment]
Good idea: fixed! 2b05310
