### ISSUE TITLE
Does this app need Postgres?

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/ivr-phone-tree-rails#2]
It looks like this iteration of the app doesn't need a database, but the README instructions still tell you to set one up and the `app.json` also includes one.

If you do plan to keep Postgres as a dependency for this version of the app, I ran into some trouble in the README because `rake db:create` made a database called `ivr-rails_test` but `rake db:migrate` wanted `ivr-rails_development`. So I had to create `ivr-rails_development` manually to get through the setup.

**Comment by jarodreyes** [comment]
Fixed. Removed postgres. a58f87f
