### ISSUE TITLE
Consider adding a "Thank you" route to end every call

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/ivr-phone-tree-rails#3]
This is minor, but I might consider adding a "goodbye" stage that happens at the end of each path through the IVR.

I felt caught off guard a little by the app hanging up on me after the directions ending. And right now the planet selection endings play once, then play again, then hang up - I was expecting them to either play once and hang up, or loop forever.

A final route for each path that makes it clear the IVR is over. Maybe something like:

    "Thank you for calling the ET Phone Home Service - the adventurous alien's first choice in intergalactic travel."

**Comment by atbaker** [comment]
You might also include an option to restart from the top menu for people who were intrigued enough (like me) to want to hear every option

**Comment by jarodreyes** [comment]
Fixed. 0e9f8ce
