### ISSUE TITLE
Fix link in "Respond to the Phone Call" step

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/ivr-phone-tree-rails#6]
It looks like you're trying to link "Twilio Numbers" to something in this step, but I wasn't exactly sure what you wanted it to link to, so I didn't include a fix in the PR.

https://github.com/TwilioDevEd/ivr-phone-tree-rails/blob/gh-pages/tutorial/index.jade#L36-L37

**Comment by jarodreyes** [comment]
Fixed: e7ccde4
