### ISSUE TITLE
Should the action in `list_planets` be `planets_path`?

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/ivr-phone-tree-rails#8]
In the TwiML you make here, you use `menu_path` as the action URL:

https://github.com/TwilioDevEd/ivr-phone-tree-rails/blob/master/app/controllers/twilio_controller.rb#L14

And in the TwiML you make here, you use `'/ivr/planets'` as the action URL:

https://github.com/TwilioDevEd/ivr-phone-tree-rails/blob/master/app/controllers/twilio_controller.rb#L47

Would it be better to use `planets_path`? Or were you doing it both ways to show that this TwiML parameter is flexible?

**Comment by jarodreyes** [comment]
Fixed: 7e274a0
